#!/usr/bin/env sh
# This file is part of couchapp released under the Apache 2 license. 
# See the NOTICE for more information.

PYTHON_BIN=`which python`

$PYTHON_BIN -OO -c "import couchapp.dispatch"
